#!/bin/bash
set -x

cmd="$1"
shift

if [[ "$cmd" = init ]] ; then
    git init
    git annex init

elif [[ "$cmd" = clone ]] ; then
    path="$1"
    shift
    dest="$1"
    shift

    git clone "$path" "$dest"
    cd "$dest"
    git annex init
    git annex sync
    git annex get .

elif [[ "$cmd" = add ]] ; then
    path="$1"
    shift

    git annex add "$@"
    git annex sync

elif [[ "$cmd" = sync ]] ; then
    git annex sync

else
    echo "no command given"
fi
