#!/bin/bash
set -x

# This is just the git remote name
DEFAULT_REMOTE=allas

_autosync () { git annex sync --no-commit "$@" ; }

cmd="$1"
shift

if [[ "$cmd" = init ]] ; then
    test -e ./.git || git init
    git annex init

elif [[ "$cmd" = clone ]] ; then
    # Clone a repository and get ALL data.  It is probably better to
    # "git clone" and "git data init", and get just the data you need.
    path="$1"
    shift
    dest="$1"
    shift

    git clone "$path" "$dest"
    cd "$dest"
    git annex init
    _autosync
    git annex get .
    _autosync

elif [[ "$cmd" = list ]] ; then
    git annex "$cmd" "$@"

elif [    "$cmd" = add \
       -o "$cmd" = get \
       -o "$cmd" = drop \
       -o "$cmd" = lock \
       -o "$cmd" = unlock \
        ] ; then
    git annex $cmd "$@"
    _autosync

elif [[ "$cmd" = push ]] ; then
    git annex copy -t $DEFAULT_REMOTE "$@"
    _autosync

elif [[ "$cmd" = metasync ]] ; then
    _autosync "$@"
    git annex fix

elif [[ "$cmd" = sync ]] ; then
    git annex sync --commit --content "$@"
    git annex fix

elif [[ "$cmd" = allas ]] ; then
    # Remote already exists - just enable it.
    if git annex info | grep -- "-- $DEFAULT_REMOTE" &>/dev/null ; then
	git annex enableremote $DEFAULT_REMOTE
	exit 1
    fi
    # Create a new special remote
    encryption="encryption=none"
    if [[ "$1" = "-e" ]] ; then
	encryption="encryption=shared"
	shift
    fi
    if [[ "$1" = "-t" ]] ; then
	exporttree="exporttree=yes importtree=yes"
	shift
    fi
    bucket="$1"
    if [[ -z "$bucket" ]] ; then
	echo "bucket must be specified"
	exit 1
    fi
    shift
    git annex initremote $DEFAULT_REMOTE type=external externaltype=rclone \
	$exporttree \
        rclone_layout=lower \
	$encryption \
        target=allas prefix="$bucket"
    # chunk=50MiB
    git annex wanted $DEFAULT_REMOTE anything

elif [[ "$cmd" = _uninit ]] ; then
    tmp=$RANDOM$RANDOM$RANDOM
    git annex dead $DEFAULT_REMOTE
    git annex renameremote $DEFAULT_REMOTE dead-$DEFAULT_REMOTE-$tmp
    git remote rename $DEFAULT_REMOTE dead-$DEFAULT_REMOTE-$tmp

else
    echo "no command given"
fi
